### ISSUE TITLE
Uncaught ReferenceError: target is not defined

### ISSUE THREAD

**Issue by mattinsler** [AlexeySokolov/atom-smart-template#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-smart-template](https://github.com/AlexeySokolov/atom-smart-template) package, v0.2.1

### Stack Trace

Uncaught ReferenceError: target is not defined

```
At /Users/mattinsler/.atom/packages/atom-smart-template/lib/atom-smart-template.coffee:86

ReferenceError: target is not defined
  at Object.module.exports.AtomSmartTemplate.createFilesFromTemplate (/Users/mattinsler/.atom/packages/atom-smart-template/lib/atom-smart-template.coffee:86:5)
  at HTMLLIElement.<anonymous> (/Users/mattinsler/.atom/packages/atom-smart-template/lib/atom-smart-template.coffee:28:124)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:172:33)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -8:41.5.0 atom-smart-template:open-temlates-folder-in-atom (atom-text-editor.editor)
  2x -4:28.5.0 atom-smart-template:create-files-from-template (div.header.list-item)
     -1:15.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:14.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:14.5.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:05.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.1.0 atom-smart-template:create-files-from-template (span.)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "ignoredNames": [
      "node_modules"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.7.0
atom-smart-template, v0.2.1
language-api-blueprint, v1.0.2
language-graphql, v0.2.0
linter, v1.11.4
linter-eslint, v7.1.1
nuclide, v0.125.0
react, v0.12.10
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by believer** [comment]
This seems to be related to Nuclide, once I disabled it the error disappeared and it started working!

**Comment by sigurdsvela** [comment]
Has this been checked out? Is there any plan to?
Love the plugin with all my heart, but it's kinda annoying to have to disable Nuclide every time I need to create a new component

**Comment by AlexeySokolov** [comment]
Thank you. I'll check this error.

**Comment by sigurdsvela** [comment]
Was a solution found? :)

**Comment by AlexeySokolov** [comment]
I couldn't reproduce the error. But I made changes that potentially have to fix it.
