### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by OpperDev** [AlexeySokolov/atom-smart-template#16]
You have some dependencies that's makes errors, like here in 'fuzzaldrin' :

```
TypeError: string.indexOf is not a function
    at Object.exports.score (C:\Users\compaq\.atom\packages\atom-smart-template\node_modules\fuzzaldrin\lib\scorer.js:60:31)
    at module.exports (C:\Users\compaq\.atom\packages\atom-smart-template\node_modules\fuzzaldrin\lib\filter.js:25:24)
    at filter (C:\Users\compaq\.atom\packages\atom-smart-template\node_modules\fuzzaldrin\lib\fuzzaldrin.js:21:14)
    at MySelectListView.module.exports.SelectListView.populateList (C:\Users\compaq\.atom\packages\atom-beautify\node_modules\atom-space-pen-views\lib\select-list-view.js:195:25)
    at C:\Users\compaq\.atom\packages\atom-beautify\node_modules\atom-space-pen-views\lib\select-list-view.js:350:26
```
That error comes when I create files from templates, it ask me the name, and when I type a char, that error spawn.

Could you fix it?

**Comment by Sai-Tumuluri** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-smart-template](https://github.com/AlexeySokolov/atom-smart-template) package 0.3.2


### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At C:\Users\stumuluri\.atom\packages\atom-smart-template\node_modules\fuzzaldrin\lib\scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at MySelectListView.module.exports.SelectListView.populateList (/packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at /packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
     -6:08.0 atom-smart-template:open-temlates-folder (div.tool-panel.tree-view)
     -5:55.1.0 atom-smart-template:open-temlates-folder-in-atom (div.tool-panel.tree-view)
     -4:29.6.0 intentions:highlight (input.hidden-input)
     -4:29.3.0 core:copy (input.hidden-input)
     -3:01.7.0 tree-view:add-file (span.name.icon.icon-repo)
  2x -2:05.4.0 atom-smart-template:create-files-from-template (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-overtype-mode 0.4.0 
atom-smart-template 0.3.2 
autoclose-html 0.23.0 
autocomplete-python 1.16.0 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
colorblind-wombat-dark-syntax 0.6.0 
file-icons 2.1.35 
file-templates 0.2.0 
intentions 1.1.5 
kite 0.170.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
script 3.18.1 
```
