### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by d4rkl1gh7** [AlexeySokolov/atom-smart-template#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-smart-template](https://github.com/AlexeySokolov/atom-smart-template) package 0.3.2

### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At /Users/briangilbert/.atom/packages/atom-smart-template/node_modules/fuzzaldrin/lib/scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (/packages/atom-smart-template/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at MySelectListView.module.exports.SelectListView.populateList (/packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at /packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
     -2:08.7.0 core:cut (input.hidden-input)
     -1:58 core:move-up (input.hidden-input)
     -1:56.3.0 core:paste (input.hidden-input)
  3x -1:50.1.0 editor:newline (input.hidden-input)
     -1:48.8.0 core:move-up (input.hidden-input)
     -1:40.7.0 editor:newline (input.hidden-input)
     -1:33 core:move-right (input.hidden-input)
     -1:31 editor:newline (input.hidden-input)
     -1:12.2.0 core:cut (input.hidden-input)
     -1:10 core:paste (input.hidden-input)
     -1:05.8.0 editor:newline (input.hidden-input)
     -0:55.8.0 core:cut (input.hidden-input)
     -0:48.7.0 core:paste (input.hidden-input)
     -0:46.8.0 core:move-down (input.hidden-input)
     -0:15.3.0 atom-smart-template:create-files-from-template (div.header.list-item)
  3x -0:08.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.1 
atom-beautify 0.29.17 
atom-live-server 2.1.1 
atom-react-preview 2.0.0 
atom-smart-template 0.3.2 
atom-typescript 10.1.14 
ax-monokai-syntax 0.1.0 
browser-refresh 0.9.0 
language-babel 2.54.1 
language-ejs 0.4.0 
linter 1.11.23 
local-server-express 0.3.1 
local-server-web-view 1.1.0 
node-debugger 1.10.1 
node-requirer 0.1.12 
nodejs-snippets 2.0.2 
nord-atom-ui 0.10.1 
open-in-browser 0.4.7 
pretty-json 1.6.1 
project-manager 3.3.3 
react 0.16.2 
react-snippets 0.7.0 
requirejs-snippets 0.1.0 
smart-tags 0.1.5 
template-generator 0.15.0 
threejs-snippets 0.0.8 
typescript-modules-helper 0.7.0 
uglify 1.3.1 
```

**Comment by amirtcheva** [comment]
I had the same issue when I tried creating a React template file...Seems like it can only process .html files, not .js. Wonder if that's the issue.

**Comment by mcneela86** [comment]
I am having this issue just trying to use the Base template after freshly installing the package. Is there any timeline on a fix?

**Comment by TomMargrave** [comment]
I am having issue also.

**Comment by raymacz** [comment]
Windows 10 - same issue - Uncaught TypeError: string.indexOf is not a function
